CREATE TABLE TBLKULLANICI(
  LNGKOD INT PRIMARY KEY NOT NULL,
  TXTAD NVARCHAR(100) NOT NULL,
  TXTSOYAD NVARCHAR(100) NOT NULL,
  TXTTELEFONNO NVARCHAR(20) NOT NULL,
  TXTEMAIL NVARCHAR(150) NOT NULL,
  TXTUNVAN NVARCHAR(150) NOT NULL,
);